package cli

import (
	"bufio"
	_"embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/joegabby/alibi/cli/internal/cli/helpers"
	"github.com/joegabby/alibi/cli/internal/cli/types"
	"github.com/manifoldco/promptui"
	"github.com/spf13/cobra"
	"golang.org/x/term"
	"gopkg.in/yaml.v3"
)

var cachedConfig *types.Config // store loaded config globally

//go:embed sample/config_sample.yml
var sampleConfig []byte

func init() {
	rootCmd.AddCommand(initCmd)
}

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize Alibi in the current Git project",
	RunE: func(cmd *cobra.Command, args []string) error {
		// ✅ Ensure inside Git repo
		cwd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("failed to get working directory: %w", err)
		}

		gitDir := filepath.Join(cwd, ".git")
		if _, err := os.Stat(gitDir); os.IsNotExist(err) {
			return fmt.Errorf("❌ No .git directory found — please run `git init` first")
		}

		// ✅ Ensure Git remote exists
		cmdGit, err := helpers.RunGit("remote", "-v")
		if err != nil || strings.TrimSpace(cmdGit) == "" {
			return fmt.Errorf("❌ No remote found — please set one using `git remote add origin <repo_url>`")
		}
		fmt.Println("✅ Git remote detected.")

		// ✅ Prevent overwriting existing config
		configFile := filepath.Join(cwd, "alibi.yml")
		if _, err := os.Stat(configFile); err == nil {
			return fmt.Errorf("⚠️ alibi.yml already exists in this directory. To reinitialize, delete it first.")
		}

		// ✅ Get project name
		reader := bufio.NewReader(os.Stdin)
		fmt.Print("💡 Enter your project name: ")
		projectNameInput, _ := reader.ReadString('\n')
		projectNameInput = strings.TrimSpace(projectNameInput)
		if projectNameInput == "" {
			return fmt.Errorf("project name cannot be empty")
		}

		// ✅ Load from embedded sample config
		var cfg types.Config
		if err := yaml.Unmarshal(sampleConfig, &cfg); err != nil {
			return fmt.Errorf("failed to load sample config: %w", err)
		}

		// ✅ Sanitize project name
		re := regexp.MustCompile(`[^a-zA-Z0-9_]+`)
		safeName := re.ReplaceAllString(projectNameInput, "_")
		cfg.Project.Name = safeName

		// ✅ Build alibi project directory
		execPath, err := os.Executable()
		if err != nil {
			return fmt.Errorf("failed to get executable path: %w", err)
		}
		binDir := filepath.Dir(execPath)
		alibiRoot := filepath.Dir(binDir)

		projectDir := filepath.Join(alibiRoot, "projects", safeName)
		cfg.Project.Data = projectDir
		cfg.Project.Source = cwd

		if err := os.MkdirAll(projectDir, 0755); err != nil {
			return fmt.Errorf("failed to create project directory: %w", err)
		}
		fmt.Println("📁 Project directory created at:", projectDir)

		// ✅ Select remote and repo
		lines := strings.Split(cmdGit, "\n")
		seen := make(map[string]bool)
		var gitRemotes []string

		for _, line := range lines {
			if strings.TrimSpace(line) == "" {
				continue
			}
			parts := strings.Fields(line)
			if len(parts) < 2 {
				continue
			}
			remoteName := parts[0]
			remoteURL := parts[1]
			if !seen[remoteName] {
				gitRemotes = append(gitRemotes, fmt.Sprintf("%s -> %s", remoteName, remoteURL))
				seen[remoteName] = true
			}
		}

		selectRepo, err := safeSelect("Select repo and remote to work with", gitRemotes)
		if err != nil {
			return fmt.Errorf("prompt failed: %v", err)
		}

		splitted := strings.Split(selectRepo, " -> ")
		cfg.Tracking.Remote = splitted[0]
		cfg.Tracking.Repo = splitted[1]

		// ✅ Write generated config file
		updatedYAML, err := yaml.Marshal(&cfg)
		if err != nil {
			return fmt.Errorf("failed to marshal config: %w", err)
		}

		if err := os.WriteFile(configFile, updatedYAML, 0600); err != nil {
			return fmt.Errorf("failed to write config file: %w", err)
		}
		fmt.Println("📝 Config file created:", configFile)

		// ✅ Setup Git Hooks
		pushHookPath := filepath.Join(gitDir, "hooks", "pre-push")
		pushScript := `#!/bin/sh
# Auto-generated by Alibi CLI
echo "🔍 Running alibi before push..."
alibi track --event=push
`
		if err := ensureHook(pushHookPath, pushScript); err != nil {
			return err
		}

		postCommitHookPath := filepath.Join(gitDir, "hooks", "post-commit")
		postCommitScript := `#!/bin/sh
# Auto-generated by Alibi CLI
echo "🔍 Running alibi after commit..."
alibi track --event=commit
`
		if err := ensureHook(postCommitHookPath, postCommitScript); err != nil {
			return err
		}

		ProjectInfo := filepath.Join(projectDir, "info.txt")
		JSONConfig, _ := json.Marshal(&cfg)
		if err := writeToFile(ProjectInfo, string(JSONConfig)); err != nil {
			return err
		}

		fmt.Println("\n✅ Alibi initialized successfully!")

		setupAI, err := safeSelect("Would you like to setup an AI provider now ?", []string{"Yes", "No"})
		if err != nil {
			return fmt.Errorf("prompt failed: %v", err)
		}
		if setupAI == "Yes" {
			var AIProviders = []string{"OpenAI", "DeepSeek", "OpenRouter", "HuggingFace"}
			selectedProvider, err := safeSelect("Select an AI Provider", AIProviders)
			if err != nil {
				return fmt.Errorf("prompt failed: %v", err)
			}

			fmt.Print("💡 Enter your ", selectedProvider, " API Key: ")
			apiKeyInput, _ := reader.ReadString('\n')
			apiKeyInput = strings.TrimSpace(apiKeyInput)

			// Read the config file
			data, err := os.ReadFile(configFile)
			if err != nil {
				return fmt.Errorf("failed to read config: %v", err)
			}
			// Unmarshal to map for easy manipulation
			var raw map[string]interface{}

			err = yaml.Unmarshal(data, &raw)
			if err != nil {
				return fmt.Errorf("failed to parse YAML: %v", err)
			}

			aiProvidersRaw, ok := raw["AIProviders"].(map[string]interface{})
			if !ok || aiProvidersRaw == nil {
				aiProvidersRaw = make(map[string]interface{})
				raw["AIProviders"] = aiProvidersRaw
			}

			aiProvidersRaw[selectedProvider] = apiKeyInput

			// Marshal back to YAML
			newYaml, err := yaml.Marshal(raw)
			if err != nil {
				return fmt.Errorf("failed to marshal YAML: %v", err)
			}

			// Write the updated config back to file
			err = os.WriteFile(configFile, newYaml, 0644)
			if err != nil {
				return fmt.Errorf("failed to write config: %v", err)
			}
			newJSONConfig, _ := json.Marshal(raw)

			ProjectInfo := filepath.Join(projectDir, "info.txt")
			if err := writeToFile(ProjectInfo, string(newJSONConfig)); err != nil {
				return err
			}

			fmt.Printf("✅ %s API key saved successfully!\n", selectedProvider)
		} else {
			fmt.Println("You can setup AI providers later from your alibi.yml file")
		}
		return nil
	},
}

func ensureHook(hookPath, script string) error {
	// Check if file exists; if not, create it with the script
	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		return os.WriteFile(hookPath, []byte(script+"\n"), 0o755)
	}

	// Read the existing file
	fileContent, err := os.ReadFile(hookPath)
	if err != nil {
		return err
	}

	// Check if script already exists
	if strings.Contains(string(fileContent), script) {
		return nil // nothing to do
	}

	// Open for append only if script is not present
	f, err := os.OpenFile(hookPath, os.O_APPEND|os.O_WRONLY, 0o755)
	if err != nil {
		return err
	}
	defer f.Close()

	_, err = f.WriteString("\n" + script + "\n")
	return err
}

func safeSelect(label string, items []string) (string, error) {
	if term.IsTerminal(int(os.Stdin.Fd())) {
		prompt := promptui.Select{Label: label, Items: items}
		_, result, err := prompt.Run()
		return result, err
	}

	fmt.Println(label + " (type number):")
	for i, v := range items {
		fmt.Printf("  [%d] %s\n", i+1, v)
	}
	reader := bufio.NewReader(os.Stdin)
	fmt.Print("> ")
	input, _ := reader.ReadString('\n')
	input = strings.TrimSpace(input)
	var index int
	fmt.Sscanf(input, "%d", &index)
	if index < 1 || index > len(items) {
		return "", fmt.Errorf("invalid selection")
	}
	return items[index-1], nil
}
